import os
import json
import ast

def load_config():
    """Load config.py dynamically and return the dictionary."""
    config_path = "config.py"
    if not os.path.exists(config_path):
        print("❌ config.py not found in the current directory.")
        return None
        
    try:
        namespace = {}
        with open(config_path, "r", encoding="utf-8") as f:
            file_content = f.read()
        exec(file_content, namespace)
        return namespace.get("CONFIG", {})
    except Exception as e:
        print(f"❌ Failed to parse config.py: {e}")
        return None

def main():
    print("🚀 Extracting profile data from config.py...")
    config = load_config()
    if not config:
        return
        
    profile = config.get("profile", {})
    if not profile:
        print("⚠️ No 'profile' dictionary found in config.py! Proceeding with empty profile.")
        
    # Extract only the necessary profile data
    ext_data = {
        "profile": profile,
        "resume_path": config.get("resume_path", ""),
        "name": config.get("name", ""),
        "email": config.get("email", ""),
        "phone": config.get("phone", "")
    }
    
    # Also grab root level attributes if they aren't in profile
    if not profile.get("name") and ext_data.get("name"):
        ext_data["profile"]["name"] = ext_data["name"]
    if not profile.get("email") and ext_data.get("email"):
        ext_data["profile"]["email"] = ext_data["email"]
    if not profile.get("phone") and ext_data.get("phone"):
        ext_data["profile"]["phone"] = ext_data["phone"]

    # Ensure output directory exists
    ext_dir = "chrome_extension"
    if not os.path.exists(ext_dir):
        os.makedirs(ext_dir)
        
    out_path = os.path.join(ext_dir, "data.js")
    
    js_content = f"// This file is auto-generated by build_extension.py\n\nconst CONFIG_DATA = {json.dumps(ext_data, indent=4)};\n"
    
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print(f"✅ Successfully exported profile data to {out_path}!")
    print("💡 The extension is now ready to be loaded in Chrome.")

if __name__ == "__main__":
    main()
